version: '3.5'

services:
  mongodb:
    image: mongo:4.2
    ports:
      - 127.0.0.1:27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
