# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Run qa
        run: make qa
      - name: Run tests
        run: make test
        env:
          key:  MOTOR_ORM_TEST_DB_CS=mongodb://mongodb:27017
